// WHATWG DOM Parsing and Serialization Standard
[*spec=DOMPARSING*]

enum [*id="supportedtype"*] SupportedType {
  "text/html",
  "text/xml",
  "application/xml",
  "application/xhtml+xml",
  "image/svg+xml"
};

[Exposed=Window]
interface [*id="domparser"*] DOMParser {
  constructor();
  [NewObject] Document [*id="dom-domparser-parsefromstring"*] parseFromString (DOMString str, SupportedType type);
};

[Exposed=Window]
interface [*id="xmlserializer"*] XMLSerializer {
  constructor();
  DOMString [*id="dom-xmlserializer-serializetostring"*] serializeToString (Node root);
};

[Exposed=Window]
partial interface Element {
  [CEReactions] attribute [TreatNullAs=EmptyString] DOMString [*id="dom-element-innerhtml"*] innerHTML;
  [CEReactions] attribute [TreatNullAs=EmptyString] DOMString [*id="dom-element-outerhtml"*] outerHTML;
  [CEReactions] void [*id="dom-element-insertAdjacentHTML"*] insertAdjacentHTML (DOMString position, DOMString text);
};

// [Exposed=Window]
// partial interface Text { attribute boolean serializeAsCDATA };

[Exposed=Window]
partial interface Range {
  [CEReactions, NewObject] DocumentFragment [*id="createcontextualfragment"*] createContextualFragment (DOMString fragment);
};
