// Vibration API <http://dev.w3.org/2009/dap/vibration/>
typedef (unsigned long or sequence<unsigned long>) VibratePattern;
partial interface Navigator {
  boolean vibrate (VibratePattern pattern);
};