// <https://w3c.github.io/deviceorientation/spec-source-orientation.html>
[Exposed=Window]
partial interface Window {
  attribute EventHandler ondeviceorientation;
  attribute EventHandler ondeviceorientationabsolute;
  attribute EventHandler ondevicemotion;
};

// <https://w3c.github.io/pointerlock/>
[Exposed=Window]
partial interface Element {
  void requestPonterLock ();
};
[Exposed=Window]
partial interface Document {
  attribute EventHandler onpointerlockchange;
  attribute EventHandler onpointerlockerror;
  void exitPointerLock ();
};
[Exposed=Window]
partial interface DocumentOrShadowRoot {
  readonly attribute Element? pointrLockElement;
};

// <https://w3c.github.io/deviceorientation/spec-source-orientation.html>
[Constructor(DOMString type, optional DeviceOrientationEventInit eventInitDict),
 Exposed=(Window)]
interface DeviceOrientationEvent : Event {
  readonly attribute double? alpha;
  readonly attribute double? beta;
  readonly attribute double? gamma;
  readonly attribute boolean absolute;
};
dictionary DeviceOrientationEventInit : EventInit {
  double? alpha = null;
  double? beta = null;
  double? gamma = null;
  boolean absolute = false;
};
[Constructor(DOMString type, optional DeviceMotionEventInit eventInitDict),
 Exposed=(Window)]
interface DeviceMotionEvent : Event {
  readonly attribute DeviceAcceleration? acceleration;
  readonly attribute DeviceAcceleration? accelerationIncludingGravity;
  readonly attribute DeviceRotationRate? rotationRate;
  readonly attribute double? interval;
};
dictionary DeviceMotionEventInit : EventInit {
  DeviceAccelerationInit? acceleration;
  DeviceAccelerationInit? accelerationIncludingGravity;
  DeviceRotationRateInit? rotationRate;
  double? interval = null;
};

// <https://w3c.github.io/pointerlock/>
[Exposed=Window]
partial interface MouseEvent {
  readonly attribute long movementX;
  readonly attribute long movementY;
};
partial dictionary MouseEventInit {
  long movementX = 0;
  long movementY = 0;
};

// <https://w3c.github.io/deviceorientation/spec-source-orientation.html>
[NoInterfaceObject, Exposed=Window]
interface DeviceAcceleration {
  readonly attribute double? x;
  readonly attribute double? y;
  readonly attribute double? z;
};
dictionary DeviceAccelerationInit {
  double? x = null;
  double? y = null;
  double? z = null;
};
[NoInterfaceObject, Exposed=Window]
interface DeviceRotationRate {
  readonly attribute double? alpha;
  readonly attribute double? beta;
  readonly attribute double? gamma;
};
dictionary DeviceRotationRateInit {
  double? alpha = null;
  double? beta = null;
  double? gamma = null;
};
