/* Web IDL builtin definitions */
[*spec=WEBIDL*]

typedef (ArrayBuffer or ArrayBufferView) ArrayBufferData;
typedef unsigned long long DOMTimeStamp;
callback Function = any (any... arguments);
callback VoidFunction = void ();
