// <https://w3c.github.io/hr-time/>

[Exposed=(Window, Worker)]
interface Performance : EventTarget {
  DOMHighResTimeStamp now ();
  DOMHighResTimeStamp translateTime
      (DOMHighResTimeStamp time,
       (Window or Worker or SharedWorker or ServiceWorker) timeSource);
  [Default] object toJSON ();
};

[Exposed=(Window, Worker)]
partial interface WindowOrWorkerGlobalScope {
  [Replaceable] readonly attribute Performance performance;
};
