[Exposed=Window]
interface XPathExpression {
  XPathResult evaluate(Node contextNode,
                       optional unsigned short type = 0,
                       optional object? result = null);
};

[Exposed=Window]
interface XPathNSResolver {
  DOMString? lookupNamespaceURI(DOMString? prefix);
};